### ISSUE TITLE
Ended maintenance of the SDK 

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/dropbox-writer-v2#2]
SDK se prý už nebude dál udržovat: https://github.com/Alorel/dropbox-v2-php#maintainers-needed Kromě něj Dropbox doporučuje ještě tohle: https://github.com/kunalvarma05/dropbox-php-sdk

**Comment by kacurez** [comment]
tjn ja som to pouzil pri prepise pretoze malo rovnake api ako to sdk predtym(v1).
